version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Setup Heroku deployment evironment
          command: |
            sudo npm install -g heroku
            cat >~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            EOF
            sudo chmod 600 ~/.netrc
            heroku -v
            heroku container:login
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app -f Dockerfile.heroku .
      - run:
          name: Deploy to Heroku
          command: |
            docker tag app registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web
            heroku container:release --app $HEROKU_APP_NAME web
